services:
    nginx:
        container_name: nginx
        env_file:
            - .env
        build:
            context: ./requirements/nginx
        image: nginx:inception
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www:ro
        networks:
            - inception
        ports:
            - 443:443
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build:
            context: ./requirements/mariadb
            args:
                DEBIAN_VERSION: ${DEBIAN_VERSION}
        image: mariadb:inception
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        expose:
            - 3306
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        env_file:
            - .env
        build:
            context: ./requirements/wordpress
        image: wordpress:inception
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_started
        volumes:
            - wordpress:/var/www
        networks:
            - inception
        expose:
            - 9000
        restart: unless-stopped

    redis:
        container_name: redis
        env_file:
            - .env
        build:
            context: ./requirements/redis
        image: redis:inception
        networks:
            - inception
        expose:
            - 6379
        restart: unless-stopped

    vsftpd:
        container_name: vsftpd
        env_file:
            - .env
        build:
            context: ./requirements/vsftpd
        image: vsftpd:inception
        networks:
            - inception
        volumes:
            - wordpress:/data
        ports:
            - 20:20
            - 21:21
            - 21100-21110:21100-21110
        restart: unless-stopped

    adminer:
        container_name: adminer
        env_file:
            - .env
        build:
            context: ./requirements/adminer
        image: adminer:inception
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - inception
        expose:
            - 9000
        restart: unless-stopped

    static:
        container_name: static
        build:
            context: ./requirements/static
        image: static:inception
        networks:
            - inception
        ports:
            - 8080:80
        restart: unless-stopped
networks:
    inception:
        name: inception
        driver: bridge

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            o: bind,nocopy
            device: ${HOME}/data/mariadb

    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind,nocopy
            device: ${HOME}/data/wordpress
