services:
    nginx:
        container_name: nginx
        env_file:
            - .env
        build:
            context: ./requirements/nginx
        image: nginx:inception
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www
        networks:
            - inception
        ports:
            - 443:443
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build:
            context: ./requirements/mariadb
            args:
                DEBIAN_VERSION: ${DEBIAN_VERSION}
        image: mariadb:inception
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - wordpress_db:/var/lib/mysql
        networks:
            - inception
        expose:
            - 3306
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        env_file:
            - .env
        build:
            context: ./requirements/wordpress
        image: wordpress:inception
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - wordpress_data:/var/www
        networks:
            - inception
        expose:
            - 9000
        restart: unless-stopped

networks:
    inception:
        driver: bridge

volumes:
    wordpress_db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress_db

    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress
